baseURL: "https://zynalkhan.github.io/blog/"
languageCode: en-us
title: ZK
theme: PaperMod

menu:
    main:
        - name: Search
            url: search/
            weight: 5

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    defaultTheme: auto
    disableThemeToggle: false
    ShowReadingTime: true
    disableSpecial1stPost: true
    ShowToc: true
    tocopen: true