baseURL: "https://zynalkhan.github.io/blog/"
languageCode: en-us
title: ZK
theme: PaperMod

menu:
  main:
    - identifier: search
      name: Search
      url: search/
      weight: 10

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  disableSpecial1stPost: true
  ShowToc: true
  tocopen: true